// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Address documents
 */
interface AddressDocumentData {
  /**
   * ZYC field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ZYC
   * - **API ID Path**: address.zyc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  zyc: prismic.RichTextField;

  /**
   * Name Full field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Zurich Youth Classical
   * - **API ID Path**: address.name_full
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_full: prismic.RichTextField;

  /**
   * Location Link field in *Address*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Location Link
   * - **API ID Path**: address.location_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Street field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brunnenhof
   * - **API ID Path**: address.street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  street: prismic.RichTextField;

  /**
   * City field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CH - 8048 Zürich
   * - **API ID Path**: address.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  city: prismic.RichTextField;
}

/**
 * Address document from Prismic
 *
 * - **API ID**: `address`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AddressDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AddressDocumentData>,
    "address",
    Lang
  >;

type DatenschutzDocumentDataSlicesSlice = never;

/**
 * Content for Datenschutz documents
 */
interface DatenschutzDocumentData {
  /**
   * Slice Zone field in *Datenschutz*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: datenschutz.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DatenschutzDocumentDataSlicesSlice> /**
   * Meta Title field in *Datenschutz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: datenschutz.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Datenschutz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: datenschutz.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Datenschutz*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: datenschutz.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Datenschutz document from Prismic
 *
 * - **API ID**: `datenschutz`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DatenschutzDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DatenschutzDocumentData>,
    "datenschutz",
    Lang
  >;

type DeinWegDocumentDataSlicesSlice = never;

/**
 * Content for Dein Weg mit ZYC documents
 */
interface DeinWegDocumentData {
  /**
   * Slice Zone field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dein_weg.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DeinWegDocumentDataSlicesSlice> /**
   * Meta Title field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dein_weg.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dein_weg.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dein_weg.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Dein Weg mit ZYC document from Prismic
 *
 * - **API ID**: `dein_weg`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeinWegDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DeinWegDocumentData>,
    "dein_weg",
    Lang
  >;

/**
 * Content for Download Bar documents
 */
interface DownloadBarDocumentData {
  /**
   * Is Download Available field in *Download Bar*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: download_bar.is_download_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  is_download_available: prismic.SelectField<
    "Stundenplan" | "Resultate" | "Nichts"
  >;

  /**
   * Schedule is Available field in *Download Bar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Der Stundenplan ist jetzt verfügbar!
   * - **API ID Path**: download_bar.schedule_is_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  schedule_is_available: prismic.KeyTextField;

  /**
   * Results are available field in *Download Bar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Die Resultate sind jetzt verfügbar!
   * - **API ID Path**: download_bar.results_are_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  results_are_available: prismic.KeyTextField;

  /**
   * Results Link field in *Download Bar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Download
   * - **API ID Path**: download_bar.results_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  results_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Schedule Link field in *Download Bar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Download
   * - **API ID Path**: download_bar.schedule_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  schedule_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Download Bar document from Prismic
 *
 * - **API ID**: `download_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DownloadBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DownloadBarDocumentData>,
    "download_bar",
    Lang
  >;

type FaqDocumentDataSlicesSlice = never;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

type ImpresssumDocumentDataSlicesSlice = never;

/**
 * Content for Impresssum documents
 */
interface ImpresssumDocumentData {
  /**
   * Slice Zone field in *Impresssum*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: impresssum.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ImpresssumDocumentDataSlicesSlice> /**
   * Meta Title field in *Impresssum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: impresssum.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Impresssum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: impresssum.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Impresssum*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: impresssum.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Impresssum document from Prismic
 *
 * - **API ID**: `impresssum`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpresssumDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ImpresssumDocumentData>,
    "impresssum",
    Lang
  >;

type KontaktDocumentDataSlicesSlice = never;

/**
 * Content for Kontakt documents
 */
interface KontaktDocumentData {
  /**
   * Slice Zone field in *Kontakt*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KontaktDocumentDataSlicesSlice> /**
   * Meta Title field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kontakt.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kontakt.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kontakt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kontakt document from Prismic
 *
 * - **API ID**: `kontakt`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontaktDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KontaktDocumentData>,
    "kontakt",
    Lang
  >;

/**
 * Content for Landing Background Image documents
 */
interface LandingBackgroundImageDocumentData {
  /**
   * Image field in *Landing Background Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_background_image.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Landing Background Image document from Prismic
 *
 * - **API ID**: `landing_background_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingBackgroundImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingBackgroundImageDocumentData>,
    "landing_background_image",
    Lang
  >;

/**
 * Content for Logo documents
 */
interface LogoDocumentData {
  /**
   * image field in *Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Logo document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LogoDocumentData>, "logo", Lang>;

/**
 * Item in *Low Navigation → Low Navigation Items*
 */
export interface LowNavigationDocumentDataLowNavigationItemsItem {
  /**
   * item field in *Low Navigation → Low Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: low_navigation.low_navigation_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Low Navigation documents
 */
interface LowNavigationDocumentData {
  /**
   * Low Navigation Items field in *Low Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: low_navigation.low_navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  low_navigation_items: prismic.GroupField<
    Simplify<LowNavigationDocumentDataLowNavigationItemsItem>
  >;
}

/**
 * Low Navigation document from Prismic
 *
 * - **API ID**: `low_navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LowNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LowNavigationDocumentData>,
    "low_navigation",
    Lang
  >;

/**
 * Item in *Navbar → Navigation Items*
 */
export interface NavbarDocumentDataNavigationItemsItem {
  /**
   * Item field in *Navbar → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: navbar.navigation_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Navigation Items field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_items: prismic.GroupField<
    Simplify<NavbarDocumentDataNavigationItemsItem>
  >;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

/**
 * Content for Navigation Indicator documents
 */
interface NavigationIndicatorDocumentData {
  /**
   * image field in *Navigation Indicator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_indicator.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Navigation Indicator document from Prismic
 *
 * - **API ID**: `navigation_indicator`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationIndicatorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationIndicatorDocumentData>,
    "navigation_indicator",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Subnavigation → Subnavigation Items*
 */
export interface SubnavigationDocumentDataSubnavigationItemsItem {
  /**
   * Link field in *Subnavigation → Subnavigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The Contest
   * - **API ID Path**: subnavigation.subnavigation_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Subnavigation documents
 */
interface SubnavigationDocumentData {
  /**
   * Subnavigation Items field in *Subnavigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: subnavigation.subnavigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  subnavigation_items: prismic.GroupField<
    Simplify<SubnavigationDocumentDataSubnavigationItemsItem>
  >;
}

/**
 * Subnavigation document from Prismic
 *
 * - **API ID**: `subnavigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubnavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubnavigationDocumentData>,
    "subnavigation",
    Lang
  >;

type TeilnahmeTermineDocumentDataSlicesSlice = never;

/**
 * Content for Teilnahme Termine documents
 */
interface TeilnahmeTermineDocumentData {
  /**
   * Slice Zone field in *Teilnahme Termine*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teilnahme_termine.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeilnahmeTermineDocumentDataSlicesSlice> /**
   * Meta Title field in *Teilnahme Termine*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teilnahme_termine.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Teilnahme Termine*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teilnahme_termine.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Teilnahme Termine*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teilnahme_termine.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Teilnahme Termine document from Prismic
 *
 * - **API ID**: `teilnahme_termine`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeilnahmeTermineDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeilnahmeTermineDocumentData>,
    "teilnahme_termine",
    Lang
  >;

type TheCadenzaDocumentDataSlicesSlice = never;

/**
 * Content for The Cadenza documents
 */
interface TheCadenzaDocumentData {
  /**
   * Slice Zone field in *The Cadenza*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_cadenza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheCadenzaDocumentDataSlicesSlice> /**
   * Meta Title field in *The Cadenza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_cadenza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Cadenza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_cadenza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Cadenza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_cadenza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Cadenza document from Prismic
 *
 * - **API ID**: `the_cadenza`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheCadenzaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheCadenzaDocumentData>,
    "the_cadenza",
    Lang
  >;

type TheContestDocumentDataSlicesSlice = never;

/**
 * Content for The Contest documents
 */
interface TheContestDocumentData {
  /**
   * Slice Zone field in *The Contest*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_contest.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheContestDocumentDataSlicesSlice> /**
   * Meta Title field in *The Contest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_contest.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Contest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_contest.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Contest*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_contest.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Contest document from Prismic
 *
 * - **API ID**: `the_contest`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheContestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheContestDocumentData>,
    "the_contest",
    Lang
  >;

type TheCrescendoDocumentDataSlicesSlice = never;

/**
 * Content for The Crescendo documents
 */
interface TheCrescendoDocumentData {
  /**
   * Slice Zone field in *The Crescendo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_crescendo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheCrescendoDocumentDataSlicesSlice> /**
   * Meta Title field in *The Crescendo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_crescendo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Crescendo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_crescendo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Crescendo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_crescendo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Crescendo document from Prismic
 *
 * - **API ID**: `the_crescendo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheCrescendoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheCrescendoDocumentData>,
    "the_crescendo",
    Lang
  >;

interface TimelineBarDocumentData {}

/**
 * Timeline Bar document from Prismic
 *
 * - **API ID**: `timeline_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TimelineBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TimelineBarDocumentData>,
    "timeline_bar",
    Lang
  >;

type UberZycDocumentDataSlicesSlice = never;

/**
 * Content for Über ZYC documents
 */
interface UberZycDocumentData {
  /**
   * Slice Zone field in *Über ZYC*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: uber_zyc.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UberZycDocumentDataSlicesSlice> /**
   * Meta Title field in *Über ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: uber_zyc.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Über ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: uber_zyc.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Über ZYC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uber_zyc.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Über ZYC document from Prismic
 *
 * - **API ID**: `uber_zyc`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UberZycDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UberZycDocumentData>,
    "uber_zyc",
    Lang
  >;

export type AllDocumentTypes =
  | AddressDocument
  | DatenschutzDocument
  | DeinWegDocument
  | DownloadBarDocument
  | FaqDocument
  | ImpresssumDocument
  | KontaktDocument
  | LandingBackgroundImageDocument
  | LogoDocument
  | LowNavigationDocument
  | NavbarDocument
  | NavigationIndicatorDocument
  | PageDocument
  | SubnavigationDocument
  | TeilnahmeTermineDocument
  | TheCadenzaDocument
  | TheContestDocument
  | TheCrescendoDocument
  | TimelineBarDocument
  | UberZycDocument;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AddressDocument,
      AddressDocumentData,
      DatenschutzDocument,
      DatenschutzDocumentData,
      DatenschutzDocumentDataSlicesSlice,
      DeinWegDocument,
      DeinWegDocumentData,
      DeinWegDocumentDataSlicesSlice,
      DownloadBarDocument,
      DownloadBarDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSlicesSlice,
      ImpresssumDocument,
      ImpresssumDocumentData,
      ImpresssumDocumentDataSlicesSlice,
      KontaktDocument,
      KontaktDocumentData,
      KontaktDocumentDataSlicesSlice,
      LandingBackgroundImageDocument,
      LandingBackgroundImageDocumentData,
      LogoDocument,
      LogoDocumentData,
      LowNavigationDocument,
      LowNavigationDocumentData,
      LowNavigationDocumentDataLowNavigationItemsItem,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItemsItem,
      NavigationIndicatorDocument,
      NavigationIndicatorDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SubnavigationDocument,
      SubnavigationDocumentData,
      SubnavigationDocumentDataSubnavigationItemsItem,
      TeilnahmeTermineDocument,
      TeilnahmeTermineDocumentData,
      TeilnahmeTermineDocumentDataSlicesSlice,
      TheCadenzaDocument,
      TheCadenzaDocumentData,
      TheCadenzaDocumentDataSlicesSlice,
      TheContestDocument,
      TheContestDocumentData,
      TheContestDocumentDataSlicesSlice,
      TheCrescendoDocument,
      TheCrescendoDocumentData,
      TheCrescendoDocumentDataSlicesSlice,
      TimelineBarDocument,
      TimelineBarDocumentData,
      UberZycDocument,
      UberZycDocumentData,
      UberZycDocumentDataSlicesSlice,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
