// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Address documents
 */
interface AddressDocumentData {
  /**
   * ZYC field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ZYC
   * - **API ID Path**: address.zyc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  zyc: prismic.RichTextField;

  /**
   * Name Full field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Zurich Youth Classical
   * - **API ID Path**: address.name_full
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_full: prismic.RichTextField;

  /**
   * Location Link field in *Address*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Location Link
   * - **API ID Path**: address.location_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Street field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brunnenhof
   * - **API ID Path**: address.street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  street: prismic.RichTextField;

  /**
   * City field in *Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CH - 8048 Zürich
   * - **API ID Path**: address.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  city: prismic.RichTextField;
}

/**
 * Address document from Prismic
 *
 * - **API ID**: `address`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AddressDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AddressDocumentData>,
    "address",
    Lang
  >;

/**
 * Content for Anmeldelink documents
 */
interface AnmeldelinkDocumentData {
  /**
   * Anmeldelink field in *Anmeldelink*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: anmeldelink.anmeldelink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  anmeldelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Anmeldelink document from Prismic
 *
 * - **API ID**: `anmeldelink`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnmeldelinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AnmeldelinkDocumentData>,
    "anmeldelink",
    Lang
  >;

/**
 * Item in *CriteriaTypeSubfield → Fieldcontent*
 */
export interface CriteriatypesubfieldDocumentDataFieldcontentItem {
  /**
   * Title field in *CriteriaTypeSubfield → Fieldcontent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Zulassungskriterien
   * - **API ID Path**: criteriatypesubfield.fieldcontent[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Short Overview field in *CriteriaTypeSubfield → Fieldcontent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: The Contest findet diesen verschiedenen Disziplinen statt:
   * - **API ID Path**: criteriatypesubfield.fieldcontent[].short_overview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_overview: prismic.RichTextField;

  /**
   * Conditions field in *CriteriaTypeSubfield → Fieldcontent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: criteriatypesubfield.fieldcontent[].conditions
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conditions: prismic.RichTextField;
}

/**
 * Content for CriteriaTypeSubfield documents
 */
interface CriteriatypesubfieldDocumentData {
  /**
   * Gehört zum Slice field in *CriteriaTypeSubfield*
   *
   * - **Field Type**: Text
   * - **Placeholder**: name des slice in lowercase
   * - **API ID Path**: criteriatypesubfield.belongs_to_slice
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  belongs_to_slice: prismic.KeyTextField;

  /**
   * Fieldcontent field in *CriteriaTypeSubfield*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: criteriatypesubfield.fieldcontent[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fieldcontent: prismic.GroupField<
    Simplify<CriteriatypesubfieldDocumentDataFieldcontentItem>
  >;
}

/**
 * CriteriaTypeSubfield document from Prismic
 *
 * - **API ID**: `criteriatypesubfield`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CriteriatypesubfieldDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CriteriatypesubfieldDocumentData>,
    "criteriatypesubfield",
    Lang
  >;

type DatenschutzDocumentDataSlicesSlice = never;

/**
 * Content for Datenschutz documents
 */
interface DatenschutzDocumentData {
  /**
   * Slice Zone field in *Datenschutz*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: datenschutz.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DatenschutzDocumentDataSlicesSlice> /**
   * Meta Title field in *Datenschutz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: datenschutz.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Datenschutz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: datenschutz.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Datenschutz*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: datenschutz.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Datenschutz document from Prismic
 *
 * - **API ID**: `datenschutz`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DatenschutzDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DatenschutzDocumentData>,
    "datenschutz",
    Lang
  >;

type DeinWegDocumentDataSlicesSlice = never;

/**
 * Content for Dein Weg mit ZYC documents
 */
interface DeinWegDocumentData {
  /**
   * Slice Zone field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dein_weg.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DeinWegDocumentDataSlicesSlice> /**
   * Meta Title field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dein_weg.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dein_weg.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Dein Weg mit ZYC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dein_weg.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Dein Weg mit ZYC document from Prismic
 *
 * - **API ID**: `dein_weg`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeinWegDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DeinWegDocumentData>,
    "dein_weg",
    Lang
  >;

/**
 * Content for Download Bar documents
 */
interface DownloadBarDocumentData {
  /**
   * Is Download Available field in *Download Bar*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: download_bar.is_download_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  is_download_available: prismic.SelectField<
    "Stundenplan" | "Resultate" | "Nichts"
  >;

  /**
   * Schedule is Available field in *Download Bar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Der Stundenplan ist jetzt verfügbar!
   * - **API ID Path**: download_bar.schedule_is_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  schedule_is_available: prismic.KeyTextField;

  /**
   * Results are available field in *Download Bar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Die Resultate sind jetzt verfügbar!
   * - **API ID Path**: download_bar.results_are_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  results_are_available: prismic.KeyTextField;

  /**
   * Results Link field in *Download Bar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Download
   * - **API ID Path**: download_bar.results_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  results_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Schedule Link field in *Download Bar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Download
   * - **API ID Path**: download_bar.schedule_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  schedule_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Download Bar document from Prismic
 *
 * - **API ID**: `download_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DownloadBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DownloadBarDocumentData>,
    "download_bar",
    Lang
  >;

type FaqDocumentDataSlicesSlice = never;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *FoldoutElement → Content*
 */
export interface FoldoutelementDocumentDataContentItem {
  /**
   * Is Foldout field in *FoldoutElement → Content*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: foldoutelement.content[].is_foldout
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_foldout: prismic.BooleanField;

  /**
   * Subtopic Title field in *FoldoutElement → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldoutelement.content[].subtopic_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtopic_title: prismic.RichTextField;

  /**
   * Subtopic Description field in *FoldoutElement → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldoutelement.content[].subtopic_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtopic_description: prismic.RichTextField;
}

/**
 * Content for FoldoutElement documents
 */
interface FoldoutelementDocumentData {
  /**
   * Belongs to Foldout field in *FoldoutElement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Selber Text wie Foldout Name des Parent Foldouts
   * - **API ID Path**: foldoutelement.belongs_to_foldout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  belongs_to_foldout: prismic.KeyTextField;

  /**
   * Itemindex field in *FoldoutElement*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: foldoutelement.itemindex
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  itemindex: prismic.NumberField;

  /**
   * Foldout Element Topic field in *FoldoutElement*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Online Anmeldung, Alterskategorie, Auswahlverfahren The Cadenza
   * - **API ID Path**: foldoutelement.foldout_element_topic
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  foldout_element_topic: prismic.RichTextField;

  /**
   * Content field in *FoldoutElement*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: foldoutelement.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<FoldoutelementDocumentDataContentItem>>;
}

/**
 * FoldoutElement document from Prismic
 *
 * - **API ID**: `foldoutelement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FoldoutelementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FoldoutelementDocumentData>,
    "foldoutelement",
    Lang
  >;

/**
 * Content for Homepage Navigation documents
 */
interface HomepageNavigationDocumentData {
  /**
   * CTA Text field in *Homepage Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: [mehr]
   * - **API ID Path**: homepage_navigation.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * The Contest field in *Homepage Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The Contest
   * - **API ID Path**: homepage_navigation.the_contest
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  the_contest: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * The Cadenza field in *Homepage Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The Cadenza
   * - **API ID Path**: homepage_navigation.the_cadenza
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  the_cadenza: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * The Crescendo field in *Homepage Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The Crescendo
   * - **API ID Path**: homepage_navigation.the_crescendo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  the_crescendo: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Termine field in *Homepage Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Termine
   * - **API ID Path**: homepage_navigation.termine
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  termine: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * About field in *Homepage Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: About
   * - **API ID Path**: homepage_navigation.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  about: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Homepage Navigation document from Prismic
 *
 * - **API ID**: `homepage_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageNavigationDocumentData>,
    "homepage_navigation",
    Lang
  >;

type ImpresssumDocumentDataSlicesSlice = never;

/**
 * Content for Impresssum documents
 */
interface ImpresssumDocumentData {
  /**
   * Slice Zone field in *Impresssum*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: impresssum.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ImpresssumDocumentDataSlicesSlice> /**
   * Meta Title field in *Impresssum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: impresssum.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Impresssum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: impresssum.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Impresssum*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: impresssum.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Impresssum document from Prismic
 *
 * - **API ID**: `impresssum`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpresssumDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ImpresssumDocumentData>,
    "impresssum",
    Lang
  >;

type KontaktDocumentDataSlicesSlice = never;

/**
 * Content for Kontakt documents
 */
interface KontaktDocumentData {
  /**
   * Slice Zone field in *Kontakt*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KontaktDocumentDataSlicesSlice> /**
   * Meta Title field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kontakt.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kontakt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kontakt.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kontakt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakt.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kontakt document from Prismic
 *
 * - **API ID**: `kontakt`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontaktDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KontaktDocumentData>,
    "kontakt",
    Lang
  >;

/**
 * Content for Landing Background Image documents
 */
interface LandingBackgroundImageDocumentData {
  /**
   * Image field in *Landing Background Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_background_image.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Landing Background Image document from Prismic
 *
 * - **API ID**: `landing_background_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingBackgroundImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingBackgroundImageDocumentData>,
    "landing_background_image",
    Lang
  >;

/**
 * Content for Logo documents
 */
interface LogoDocumentData {
  /**
   * image field in *Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Logo document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LogoDocumentData>, "logo", Lang>;

/**
 * Item in *Low Navigation → Low Navigation Items*
 */
export interface LowNavigationDocumentDataLowNavigationItemsItem {
  /**
   * item field in *Low Navigation → Low Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: low_navigation.low_navigation_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Low Navigation documents
 */
interface LowNavigationDocumentData {
  /**
   * Low Navigation Items field in *Low Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: low_navigation.low_navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  low_navigation_items: prismic.GroupField<
    Simplify<LowNavigationDocumentDataLowNavigationItemsItem>
  >;
}

/**
 * Low Navigation document from Prismic
 *
 * - **API ID**: `low_navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LowNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LowNavigationDocumentData>,
    "low_navigation",
    Lang
  >;

/**
 * Item in *Navbar → Navigation Items*
 */
export interface NavbarDocumentDataNavigationItemsItem {
  /**
   * Item field in *Navbar → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: navbar.navigation_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Navigation Items field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_items: prismic.GroupField<
    Simplify<NavbarDocumentDataNavigationItemsItem>
  >;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

/**
 * Content for Navigation Indicator documents
 */
interface NavigationIndicatorDocumentData {
  /**
   * image field in *Navigation Indicator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_indicator.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Navigation Indicator document from Prismic
 *
 * - **API ID**: `navigation_indicator`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationIndicatorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationIndicatorDocumentData>,
    "navigation_indicator",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Subnavigation → Subnavigation Items*
 */
export interface SubnavigationDocumentDataSubnavigationItemsItem {
  /**
   * Link field in *Subnavigation → Subnavigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The Contest
   * - **API ID Path**: subnavigation.subnavigation_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Subnavigation documents
 */
interface SubnavigationDocumentData {
  /**
   * Subnavigation Items field in *Subnavigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: subnavigation.subnavigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  subnavigation_items: prismic.GroupField<
    Simplify<SubnavigationDocumentDataSubnavigationItemsItem>
  >;
}

/**
 * Subnavigation document from Prismic
 *
 * - **API ID**: `subnavigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubnavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubnavigationDocumentData>,
    "subnavigation",
    Lang
  >;

type TeilnahmeTermineDocumentDataSlicesSlice = never;

/**
 * Content for Teilnahme Termine documents
 */
interface TeilnahmeTermineDocumentData {
  /**
   * Slice Zone field in *Teilnahme Termine*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teilnahme_termine.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeilnahmeTermineDocumentDataSlicesSlice> /**
   * Meta Title field in *Teilnahme Termine*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teilnahme_termine.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Teilnahme Termine*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teilnahme_termine.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Teilnahme Termine*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teilnahme_termine.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Teilnahme Termine document from Prismic
 *
 * - **API ID**: `teilnahme_termine`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeilnahmeTermineDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeilnahmeTermineDocumentData>,
    "teilnahme_termine",
    Lang
  >;

type TheCadenzaDocumentDataSlicesSlice =
  | FoldoutSlice
  | SplitVisualHeadlineSlice;

/**
 * Content for The Cadenza documents
 */
interface TheCadenzaDocumentData {
  /**
   * Slice Zone field in *The Cadenza*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_cadenza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheCadenzaDocumentDataSlicesSlice> /**
   * Meta Title field in *The Cadenza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_cadenza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Cadenza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_cadenza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Cadenza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_cadenza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Cadenza document from Prismic
 *
 * - **API ID**: `the_cadenza`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheCadenzaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheCadenzaDocumentData>,
    "the_cadenza",
    Lang
  >;

type TheContestDocumentDataSlicesSlice =
  | JuryGridSlice
  | ContactAndDownloadSlice
  | CriteriasSlice
  | ContestTimelineSlice
  | FoldoutSlice
  | SplitVisualHeadlineSlice;

/**
 * Content for The Contest documents
 */
interface TheContestDocumentData {
  /**
   * Slice Zone field in *The Contest*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_contest.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheContestDocumentDataSlicesSlice> /**
   * Meta Title field in *The Contest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_contest.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Contest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_contest.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Contest*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_contest.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Contest document from Prismic
 *
 * - **API ID**: `the_contest`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheContestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheContestDocumentData>,
    "the_contest",
    Lang
  >;

type TheCrescendoDocumentDataSlicesSlice =
  | FoldoutSlice
  | SplitVisualHeadlineSlice;

/**
 * Content for The Crescendo documents
 */
interface TheCrescendoDocumentData {
  /**
   * Slice Zone field in *The Crescendo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: the_crescendo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TheCrescendoDocumentDataSlicesSlice> /**
   * Meta Title field in *The Crescendo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: the_crescendo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Crescendo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: the_crescendo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Crescendo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_crescendo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Crescendo document from Prismic
 *
 * - **API ID**: `the_crescendo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheCrescendoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheCrescendoDocumentData>,
    "the_crescendo",
    Lang
  >;

type TimelineDocumentDataSlicesSlice = TimelinePhasesSlice;

/**
 * Content for TImeline documents
 */
interface TimelineDocumentData {
  /**
   * Slice Zone field in *TImeline*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TimelineDocumentDataSlicesSlice>;
}

/**
 * TImeline document from Prismic
 *
 * - **API ID**: `timeline`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TimelineDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TimelineDocumentData>,
    "timeline",
    Lang
  >;

type UberZycDocumentDataSlicesSlice = never;

/**
 * Content for Über ZYC documents
 */
interface UberZycDocumentData {
  /**
   * Slice Zone field in *Über ZYC*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: uber_zyc.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UberZycDocumentDataSlicesSlice> /**
   * Meta Title field in *Über ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: uber_zyc.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Über ZYC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: uber_zyc.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Über ZYC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uber_zyc.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Über ZYC document from Prismic
 *
 * - **API ID**: `uber_zyc`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UberZycDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UberZycDocumentData>,
    "uber_zyc",
    Lang
  >;

/**
 * Content for We Are Here Image documents
 */
interface WeAreHereImageDocumentData {
  /**
   * image field in *We Are Here Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: we_are_here_image.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * We Are Here Image document from Prismic
 *
 * - **API ID**: `we_are_here_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WeAreHereImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WeAreHereImageDocumentData>,
    "we_are_here_image",
    Lang
  >;

export type AllDocumentTypes =
  | AddressDocument
  | AnmeldelinkDocument
  | CriteriatypesubfieldDocument
  | DatenschutzDocument
  | DeinWegDocument
  | DownloadBarDocument
  | FaqDocument
  | FoldoutelementDocument
  | HomepageNavigationDocument
  | ImpresssumDocument
  | KontaktDocument
  | LandingBackgroundImageDocument
  | LogoDocument
  | LowNavigationDocument
  | NavbarDocument
  | NavigationIndicatorDocument
  | PageDocument
  | SubnavigationDocument
  | TeilnahmeTermineDocument
  | TheCadenzaDocument
  | TheContestDocument
  | TheCrescendoDocument
  | TimelineDocument
  | UberZycDocument
  | WeAreHereImageDocument;

/**
 * Item in *ContactAndDownload → Default → Primary → Links*
 */
export interface ContactAndDownloadSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *ContactAndDownload → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Zum allgemeinen FAQ/Kontaktiere uns
   * - **API ID Path**: contact_and_download.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *ContactAndDownload → Default → Primary → Download Links*
 */
export interface ContactAndDownloadSliceDefaultPrimaryDownloadLinksItem {
  /**
   * Link field in *ContactAndDownload → Default → Primary → Download Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Name Download
   * - **API ID Path**: contact_and_download.default.primary.download_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ContactAndDownload → Default → Primary*
 */
export interface ContactAndDownloadSliceDefaultPrimary {
  /**
   * Subtitle Something Missing field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Fehlt etwas?
   * - **API ID Path**: contact_and_download.default.primary.subtitle_something_missing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle_something_missing: prismic.RichTextField;

  /**
   * Text missingsomething field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: hast du noch weitere fragene etc?
   * - **API ID Path**: contact_and_download.default.primary.text_missingsomething
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_missingsomething: prismic.RichTextField;

  /**
   * Links field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_download.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<
    Simplify<ContactAndDownloadSliceDefaultPrimaryLinksItem>
  >;

  /**
   * Downloads Title field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Downloads
   * - **API ID Path**: contact_and_download.default.primary.downloads_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  downloads_title: prismic.RichTextField;

  /**
   * Text Downloads field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Du kannst alle Reglemente und Zeitpläne zu einem gegebenen Zeitpunkt hier downloaden.
   * - **API ID Path**: contact_and_download.default.primary.text_downloads
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_downloads: prismic.RichTextField;

  /**
   * Download Links field in *ContactAndDownload → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_download.default.primary.download_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  download_links: prismic.GroupField<
    Simplify<ContactAndDownloadSliceDefaultPrimaryDownloadLinksItem>
  >;
}

/**
 * Default variation for ContactAndDownload Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndDownloadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactAndDownloadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactAndDownload*
 */
type ContactAndDownloadSliceVariation = ContactAndDownloadSliceDefault;

/**
 * ContactAndDownload Shared Slice
 *
 * - **API ID**: `contact_and_download`
 * - **Description**: ContactAndDownload
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndDownloadSlice = prismic.SharedSlice<
  "contact_and_download",
  ContactAndDownloadSliceVariation
>;

/**
 * Item in *ContestTimeline → Default → Primary → Timeline Contest Group*
 */
export interface ContestTimelineSliceDefaultPrimaryTimelineContestGroupItem {
  /**
   * Start Date field in *ContestTimeline → Default → Primary → Timeline Contest Group*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: contest_timeline.default.primary.timeline_contest_group[].start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *ContestTimeline → Default → Primary → Timeline Contest Group*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: contest_timeline.default.primary.timeline_contest_group[].end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Phase Name  field in *ContestTimeline → Default → Primary → Timeline Contest Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Anmeldung
   * - **API ID Path**: contest_timeline.default.primary.timeline_contest_group[].phase_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phase_name: prismic.RichTextField;

  /**
   * Phase Description field in *ContestTimeline → Default → Primary → Timeline Contest Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contest_timeline.default.primary.timeline_contest_group[].phase_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phase_description: prismic.RichTextField;
}

/**
 * Primary content in *ContestTimeline → Default → Primary*
 */
export interface ContestTimelineSliceDefaultPrimary {
  /**
   * Title field in *ContestTimeline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Timeline
   * - **API ID Path**: contest_timeline.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Timeline Contest Group field in *ContestTimeline → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contest_timeline.default.primary.timeline_contest_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timeline_contest_group: prismic.GroupField<
    Simplify<ContestTimelineSliceDefaultPrimaryTimelineContestGroupItem>
  >;
}

/**
 * Default variation for ContestTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContestTimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContestTimelineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContestTimeline*
 */
type ContestTimelineSliceVariation = ContestTimelineSliceDefault;

/**
 * ContestTimeline Shared Slice
 *
 * - **API ID**: `contest_timeline`
 * - **Description**: ContestTimeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContestTimelineSlice = prismic.SharedSlice<
  "contest_timeline",
  ContestTimelineSliceVariation
>;

/**
 * Primary content in *Criterias → Default → Primary*
 */
export interface CriteriasSliceDefaultPrimary {
  /**
   * Title field in *Criterias → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Zulassungskriterien
   * - **API ID Path**: criterias.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * CTA Contest field in *Criterias → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Alle Anforderungen erfüllt? Dann melde dich für THE CONTEST an!
   * - **API ID Path**: criterias.default.primary.cta_contest
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_contest: prismic.RichTextField;

  /**
   * Signup Link field in *Criterias → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Anmelden!
   * - **API ID Path**: criterias.default.primary.signup_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  signup_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Name field in *Criterias → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name des Slice in Lowercase
   * - **API ID Path**: criterias.default.primary.slice_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slice_name: prismic.KeyTextField;
}

/**
 * Default variation for Criterias Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CriteriasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CriteriasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Criterias*
 */
type CriteriasSliceVariation = CriteriasSliceDefault;

/**
 * Criterias Shared Slice
 *
 * - **API ID**: `criterias`
 * - **Description**: Criterias
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CriteriasSlice = prismic.SharedSlice<
  "criterias",
  CriteriasSliceVariation
>;

/**
 * Primary content in *Foldout → Default → Primary*
 */
export interface FoldoutSliceDefaultPrimary {
  /**
   * Section Title field in *Foldout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Weitere Fragen?
   * - **API ID Path**: foldout.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Foldout Name field in *Foldout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einen Namen für das Foldout
   * - **API ID Path**: foldout.default.primary.foldout_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  foldout_name: prismic.KeyTextField;
}

/**
 * Default variation for Foldout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FoldoutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FoldoutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Foldout → Foldout With Image → Primary*
 */
export interface FoldoutSliceFoldoutWithImagePrimary {
  /**
   * Foldout Image field in *Foldout → Foldout With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: foldout.foldoutWithImage.primary.foldout_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foldout_image: prismic.ImageField<never>;

  /**
   * Foldout Name field in *Foldout → Foldout With Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einen Namen für das Foldout
   * - **API ID Path**: foldout.foldoutWithImage.primary.foldout_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  foldout_name: prismic.KeyTextField;

  /**
   * Section_title field in *Foldout → Foldout With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldout.foldoutWithImage.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Decoration Image field in *Foldout → Foldout With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: foldout.foldoutWithImage.primary.decoration_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  decoration_image: prismic.ImageField<never>;
}

/**
 * Foldout With Image variation for Foldout Slice
 *
 * - **API ID**: `foldoutWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FoldoutSliceFoldoutWithImage = prismic.SharedSliceVariation<
  "foldoutWithImage",
  Simplify<FoldoutSliceFoldoutWithImagePrimary>,
  never
>;

/**
 * Slice variation for *Foldout*
 */
type FoldoutSliceVariation = FoldoutSliceDefault | FoldoutSliceFoldoutWithImage;

/**
 * Foldout Shared Slice
 *
 * - **API ID**: `foldout`
 * - **Description**: Foldout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FoldoutSlice = prismic.SharedSlice<
  "foldout",
  FoldoutSliceVariation
>;

/**
 * Item in *JuryGrid → Base Grid → Primary → Members*
 */
export interface JuryGridSliceBaseGridPrimaryMembersItem {
  /**
   * Photo field in *JuryGrid → Base Grid → Primary → Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.members[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Name field in *JuryGrid → Base Grid → Primary → Members*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.members[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Bio field in *JuryGrid → Base Grid → Primary → Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.members[].bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Jurymember Link field in *JuryGrid → Base Grid → Primary → Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.members[].jurymember_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  jurymember_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *JuryGrid → Base Grid → Primary*
 */
export interface JuryGridSliceBaseGridPrimary {
  /**
   * Headline field in *JuryGrid → Base Grid → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Introduction field in *JuryGrid → Base Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * Jurymember Linkicon field in *JuryGrid → Base Grid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.jurymember_linkicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  jurymember_linkicon: prismic.ImageField<never>;

  /**
   * Members field in *JuryGrid → Base Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: jury_grid.base_grid.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<
    Simplify<JuryGridSliceBaseGridPrimaryMembersItem>
  >;
}

/**
 * Base Grid variation for JuryGrid Slice
 *
 * - **API ID**: `base_grid`
 * - **Description**: A grid layout with a headline, introduction, and repeated jury/person entries featuring image, name, description, and optional links.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JuryGridSliceBaseGrid = prismic.SharedSliceVariation<
  "base_grid",
  Simplify<JuryGridSliceBaseGridPrimary>,
  never
>;

/**
 * Slice variation for *JuryGrid*
 */
type JuryGridSliceVariation = JuryGridSliceBaseGrid;

/**
 * JuryGrid Shared Slice
 *
 * - **API ID**: `jury_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JuryGridSlice = prismic.SharedSlice<
  "jury_grid",
  JuryGridSliceVariation
>;

/**
 * Item in *Hero → Contest → Primary → Contestübersicht*
 */
export interface SplitVisualHeadlineSliceContestPrimaryContestubersichtItem {
  /**
   * Item field in *Hero → Contest → Primary → Contestübersicht*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.contestubersicht[].item
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Cadenza, Crescendo → Primary*
 */
export interface SplitVisualHeadlineSliceVisualLeftHeadlineRightPrimary {
  /**
   * Visual field in *Hero → Cadenza, Crescendo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.visual_left_headline_right.primary.visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual: prismic.ImageField<never>;

  /**
   * Headline field in *Hero → Cadenza, Crescendo → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.visual_left_headline_right.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Supporting Text field in *Hero → Cadenza, Crescendo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.visual_left_headline_right.primary.supporting_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  supporting_text: prismic.RichTextField;

  /**
   * Background Color field in *Hero → Cadenza, Crescendo → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.visual_left_headline_right.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Decoration field in *Hero → Cadenza, Crescendo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.visual_left_headline_right.primary.decoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  decoration: prismic.ImageField<never>;
}

/**
 * Cadenza, Crescendo variation for Hero Slice
 *
 * - **API ID**: `visual_left_headline_right`
 * - **Description**: Displays an image to the left and headline content with description to the right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitVisualHeadlineSliceVisualLeftHeadlineRight =
  prismic.SharedSliceVariation<
    "visual_left_headline_right",
    Simplify<SplitVisualHeadlineSliceVisualLeftHeadlineRightPrimary>,
    never
  >;

/**
 * Primary content in *Hero → Contest → Primary*
 */
export interface SplitVisualHeadlineSliceContestPrimary {
  /**
   * Visual field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual: prismic.ImageField<never>;

  /**
   * Headline field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Supporting Text field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.supporting_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  supporting_text: prismic.RichTextField;

  /**
   * Background Color field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Decoration field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.decoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  decoration: prismic.ImageField<never>;

  /**
   * Anmeldelink field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Anmelden!
   * - **API ID Path**: split_visual_headline.contest.primary.anmeldelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  anmeldelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Reglement DOwnload field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Download Reglement
   * - **API ID Path**: split_visual_headline.contest.primary.reglement_download
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  reglement_download: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Contestübersicht field in *Hero → Contest → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: split_visual_headline.contest.primary.contestubersicht[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contestubersicht: prismic.GroupField<
    Simplify<SplitVisualHeadlineSliceContestPrimaryContestubersichtItem>
  >;
}

/**
 * Contest variation for Hero Slice
 *
 * - **API ID**: `contest`
 * - **Description**: Displays an image to the left and headline content with description to the right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitVisualHeadlineSliceContest = prismic.SharedSliceVariation<
  "contest",
  Simplify<SplitVisualHeadlineSliceContestPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type SplitVisualHeadlineSliceVariation =
  | SplitVisualHeadlineSliceVisualLeftHeadlineRight
  | SplitVisualHeadlineSliceContest;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `split_visual_headline`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitVisualHeadlineSlice = prismic.SharedSlice<
  "split_visual_headline",
  SplitVisualHeadlineSliceVariation
>;

/**
 * Primary content in *TimellinePhase → Long Phase → Primary*
 */
export interface TimelinePhasesSliceDefaultPrimary {
  /**
   * Phase title field in *TimellinePhase → Long Phase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Qualifikationsphase
   * - **API ID Path**: timeline_phases.default.primary.phase_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phase_title: prismic.RichTextField;

  /**
   * Start Date field in *TimellinePhase → Long Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *TimellinePhase → Long Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * width field in *TimellinePhase → Long Phase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 30%
   * - **API ID Path**: timeline_phases.default.primary.width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  width: prismic.KeyTextField;
}

/**
 * Long Phase variation for TimellinePhase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelinePhasesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelinePhasesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TimellinePhase → Mid Phase → Primary*
 */
export interface TimelinePhasesSliceMidPhasePrimary {
  /**
   * Phase title field in *TimellinePhase → Mid Phase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Qualifikationsphase
   * - **API ID Path**: timeline_phases.midPhase.primary.phase_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phase_title: prismic.RichTextField;

  /**
   * Start Date field in *TimellinePhase → Mid Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.midPhase.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *TimellinePhase → Mid Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.midPhase.primary.end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;
}

/**
 * Mid Phase variation for TimellinePhase Slice
 *
 * - **API ID**: `midPhase`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelinePhasesSliceMidPhase = prismic.SharedSliceVariation<
  "midPhase",
  Simplify<TimelinePhasesSliceMidPhasePrimary>,
  never
>;

/**
 * Primary content in *TimellinePhase → Short Phase → Primary*
 */
export interface TimelinePhasesSliceShortPhasePrimary {
  /**
   * Phase title field in *TimellinePhase → Short Phase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Qualifikationsphase
   * - **API ID Path**: timeline_phases.shortPhase.primary.phase_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phase_title: prismic.RichTextField;

  /**
   * Start Date field in *TimellinePhase → Short Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.shortPhase.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *TimellinePhase → Short Phase → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_phases.shortPhase.primary.end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;
}

/**
 * Short Phase variation for TimellinePhase Slice
 *
 * - **API ID**: `shortPhase`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelinePhasesSliceShortPhase = prismic.SharedSliceVariation<
  "shortPhase",
  Simplify<TimelinePhasesSliceShortPhasePrimary>,
  never
>;

/**
 * Slice variation for *TimellinePhase*
 */
type TimelinePhasesSliceVariation =
  | TimelinePhasesSliceDefault
  | TimelinePhasesSliceMidPhase
  | TimelinePhasesSliceShortPhase;

/**
 * TimellinePhase Shared Slice
 *
 * - **API ID**: `timeline_phases`
 * - **Description**: TimelinePhases
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelinePhasesSlice = prismic.SharedSlice<
  "timeline_phases",
  TimelinePhasesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AddressDocument,
      AddressDocumentData,
      AnmeldelinkDocument,
      AnmeldelinkDocumentData,
      CriteriatypesubfieldDocument,
      CriteriatypesubfieldDocumentData,
      CriteriatypesubfieldDocumentDataFieldcontentItem,
      DatenschutzDocument,
      DatenschutzDocumentData,
      DatenschutzDocumentDataSlicesSlice,
      DeinWegDocument,
      DeinWegDocumentData,
      DeinWegDocumentDataSlicesSlice,
      DownloadBarDocument,
      DownloadBarDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSlicesSlice,
      FoldoutelementDocument,
      FoldoutelementDocumentData,
      FoldoutelementDocumentDataContentItem,
      HomepageNavigationDocument,
      HomepageNavigationDocumentData,
      ImpresssumDocument,
      ImpresssumDocumentData,
      ImpresssumDocumentDataSlicesSlice,
      KontaktDocument,
      KontaktDocumentData,
      KontaktDocumentDataSlicesSlice,
      LandingBackgroundImageDocument,
      LandingBackgroundImageDocumentData,
      LogoDocument,
      LogoDocumentData,
      LowNavigationDocument,
      LowNavigationDocumentData,
      LowNavigationDocumentDataLowNavigationItemsItem,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItemsItem,
      NavigationIndicatorDocument,
      NavigationIndicatorDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SubnavigationDocument,
      SubnavigationDocumentData,
      SubnavigationDocumentDataSubnavigationItemsItem,
      TeilnahmeTermineDocument,
      TeilnahmeTermineDocumentData,
      TeilnahmeTermineDocumentDataSlicesSlice,
      TheCadenzaDocument,
      TheCadenzaDocumentData,
      TheCadenzaDocumentDataSlicesSlice,
      TheContestDocument,
      TheContestDocumentData,
      TheContestDocumentDataSlicesSlice,
      TheCrescendoDocument,
      TheCrescendoDocumentData,
      TheCrescendoDocumentDataSlicesSlice,
      TimelineDocument,
      TimelineDocumentData,
      TimelineDocumentDataSlicesSlice,
      UberZycDocument,
      UberZycDocumentData,
      UberZycDocumentDataSlicesSlice,
      WeAreHereImageDocument,
      WeAreHereImageDocumentData,
      AllDocumentTypes,
      ContactAndDownloadSlice,
      ContactAndDownloadSliceDefaultPrimaryLinksItem,
      ContactAndDownloadSliceDefaultPrimaryDownloadLinksItem,
      ContactAndDownloadSliceDefaultPrimary,
      ContactAndDownloadSliceVariation,
      ContactAndDownloadSliceDefault,
      ContestTimelineSlice,
      ContestTimelineSliceDefaultPrimaryTimelineContestGroupItem,
      ContestTimelineSliceDefaultPrimary,
      ContestTimelineSliceVariation,
      ContestTimelineSliceDefault,
      CriteriasSlice,
      CriteriasSliceDefaultPrimary,
      CriteriasSliceVariation,
      CriteriasSliceDefault,
      FoldoutSlice,
      FoldoutSliceDefaultPrimary,
      FoldoutSliceFoldoutWithImagePrimary,
      FoldoutSliceVariation,
      FoldoutSliceDefault,
      FoldoutSliceFoldoutWithImage,
      JuryGridSlice,
      JuryGridSliceBaseGridPrimaryMembersItem,
      JuryGridSliceBaseGridPrimary,
      JuryGridSliceVariation,
      JuryGridSliceBaseGrid,
      SplitVisualHeadlineSlice,
      SplitVisualHeadlineSliceVisualLeftHeadlineRightPrimary,
      SplitVisualHeadlineSliceContestPrimaryContestubersichtItem,
      SplitVisualHeadlineSliceContestPrimary,
      SplitVisualHeadlineSliceVariation,
      SplitVisualHeadlineSliceVisualLeftHeadlineRight,
      SplitVisualHeadlineSliceContest,
      TimelinePhasesSlice,
      TimelinePhasesSliceDefaultPrimary,
      TimelinePhasesSliceMidPhasePrimary,
      TimelinePhasesSliceShortPhasePrimary,
      TimelinePhasesSliceVariation,
      TimelinePhasesSliceDefault,
      TimelinePhasesSliceMidPhase,
      TimelinePhasesSliceShortPhase,
    };
  }
}
