// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_and_download: dynamic(() => import("./ContactAndDownload")),
  contest_timeline: dynamic(() => import("./ContestTimeline")),
  criterias: dynamic(() => import("./Criterias")),
  foldout: dynamic(() => import("./Foldout")),
  jury_grid: dynamic(() => import("./JuryGrid")),
  schedule_slice: dynamic(() => import("./ScheduleSlice")),
  split_visual_headline: dynamic(() => import("./Hero")),
  timeline_phases: dynamic(() => import("./TimellinePhase")),
};
