// Code generated by Prismic. DO NOT EDIT.

import ContactAndDownload from "./ContactAndDownload";
import ContestTimeline from "./ContestTimeline";
import Criterias from "./Criterias";
import Foldout from "./Foldout";
import GalleryYear from "./GalleryYear";
import JuryGrid from "./JuryGrid";
import ScheduleSlice from "./ScheduleSlice";
import Hero from "./Hero";
import TimellinePhase from "./TimellinePhase";
import VideosYear from "./VideosYear";

export const components = {
	contact_and_download: ContactAndDownload,
	contest_timeline: ContestTimeline,
	criterias: Criterias,
	foldout: Foldout,
	gallery_year: GalleryYear,
	jury_grid: JuryGrid,
	schedule_slice: ScheduleSlice,
	split_visual_headline: Hero,
	timeline_phases: TimellinePhase,
	videos_year: VideosYear
};