// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  split_visual_headline: dynamic(() => import("./Hero")),
  timeline_phases: dynamic(() => import("./TimellinePhase")),
};
